### ISSUE TITLE
Add option to customize audio/music volume

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/mars-patcher#19]
Would be nice to have something like 50% sfx and 100% music.

Worst case, if thats not possible, a setting to completely disable SFX/music would be fine too

**Comment by biosp4rk** [comment]
As far as I know, only disabling music is possible

**Comment by biosp4rk** [comment]
Options to disable music and sound have been added. Not possible to lower volume of one type with current knowledge.
