### ISSUE TITLE
post stable: look into randomizing the screw attack blocks leading to tube shortcuts.

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/mars-patcher#54]
could potentially lead into more interesting logic.

**Comment by biosp4rk** [comment]
Clarification: randomize the screw attack blocks in the rooms leading to tube shortcuts

**Comment by JeffGainsNGames** [comment]
Would this be:
1) all blocks for all pipes switch (ex SA to shot)
2) each set of blocks switches to a different type (ex: s1<->s2 is shot, s2<->s4 is missile)

**Comment by Miepee** [comment]
The original thought for me, was to have 1. E.g. all screw blocks -> shoot/bomb/missile/speed/power bombs

But then i very quickly realized that speed is impossible in most locations, and PBs (and speed) would make certain paths impossible after they've been broken once.

But due to the nature of Fusion seeds, Missiles and explosives are in most cases almost always early game. Which means that logically they arent really any different from shoot blocks and only complicate logic implementation.
So currently thinking about either providing screw blocks or shoot blocks, as the tubes being free could have some interesting consequences in tube shuffle later (and maybe in vanilla tubes too, but not sure).

**Comment by Miepee** [comment]
This can be now done due to #72
