### ISSUE TITLE
Tube shuffle

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/mars-patcher#66]
Opening for completionist sake. Should change the graphics near the tube to indicate where they lead to.

**Comment by biosp4rk** [comment]
Isn't this already implemented?

**Comment by Miepee** [comment]
Is it? I couldnt find it in the schema, and the TODO list still mentions this should be implemented.

**Comment by biosp4rk** [comment]
https://github.com/MetroidAdvRandomizerSystem/mars-patcher/blob/main/src/mars_patcher/connections.py#L112

**Comment by Miepee** [comment]
oh
