### ISSUE TITLE
Enabling Main boiler causes Screw SFX to not play anymore

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/mars-patcher#68]
Can fix this by reenabling SA.
I don't know if this automatically fixes itself when going through a room transition, as I have not tested that before I tried the above.

patcher json if needed, (I was playing with disabled music):
[sample.json](https://github.com/user-attachments/files/16831291/sample.json)

**Comment by biosp4rk** [comment]
Duplicate of #76
