### ISSUE TITLE
Disable music patch disables ice beam shooting sound as well

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/mars-patcher#75]
Unsure if bug or feature...

**Comment by Miepee** [comment]
On second thought, i think this was due to destroying an s1 stabilizer

**Comment by biosp4rk** [comment]
I can't repro this. Can you see if there are steps that always cause this?

**Comment by biosp4rk** [comment]
After looking at the other two issues, it must have happened after the last stabilizer was destroyed, since it plays a different sound

**Comment by biosp4rk** [comment]
Duplicate of #76
