### ISSUE TITLE
Add internal API for editing map

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/mars-patcher#83]

**Comment by biosp4rk** [comment]
1. I assume this is referring to the map on the pause screen?
2. Does "internal" mean it shouldn't be exposed via the patch data json? If so, how will it be used?

**Comment by Miepee** [comment]
1. Yes
2. I initially thought about just using it to blank out doors for DLR, but now I remembered that that needs to be done via palette editing instead. I guess we could make it public and expose it in the patch data.
