### ISSUE TITLE
Operations Deck hatch to elevator is locked when set to an open hatch

### ISSUE THREAD

**Issue by JeffGainsNGames** [MetroidAdvRandomizerSystem/mars-patcher#86]
![image](https://github.com/user-attachments/assets/b7e8d85e-108f-4cdc-8380-dd5ee75bb9b2)
[mars-data.json](https://github.com/user-attachments/files/17012286/mars-data.json)

confirmed data in the mars_data is targeting the correct door. When the door is set to a levelX hatch the door functions as expected.

**Comment by biosp4rk** [comment]
Fixed by [6dd4d5b](https://github.com/MetroidAdvRandomizerSystem/mars-patcher/commit/6dd4d5bbdcf30c44f4549457be75913d6a443e67)
