### ISSUE TITLE
Crumble City issues with DLR

### ISSUE THREAD

**Issue by JeffGainsNGames** [MetroidAdvRandomizerSystem/mars-patcher#87]
https://discord.com/channels/914291389293027329/1215675687936196608/1284615844332306463
![image](https://github.com/user-attachments/assets/6ed07dcc-7064-4052-8010-231890184c3e)

Issue appears when the door is modified to an open hatch.

**Comment by biosp4rk** [comment]
Can't repro, is this still happening?
