### ISSUE TITLE
[Fusion] Suit palette fixes, SA-X screw attack

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [MetroidAdvRandomizerSystem/mars-patcher#92]
sa-x's screw attack uses gravity instead of varia and when samus faces right, her left hand is colored blue regardless of suit

**Comment by Miepee** [comment]
Not interested in changing these. These are vanilla "bugs", and aren't worth the time to change as they are for all intents and purposes irrelevant.

**Comment by Miepee** [comment]
There is no "customizer". If you mean the randomizer, then that's dependant on the dev team's decision. If you mean the user, then no, they don't decide on the dev team's decision. 

---

Also, I want to take this opportunity and officially warn you to be a little more respectful to the developers time when opening issues. When you're creating or commenting on issues for the sake of doing it without adding anything valuable to it, it just wastes our time. 
We want the issue tracker to be open, but if the behaviour continues we will either have to block you from interacting with issues, or make the issue tracker only available to devs. None of which are things we want to do.

If you want to discuss things, either regarding the randomizer's development or regarding this message, then you can join the [Metroid Fusion Discord Guild](https://discord.gg/0fRQH1xgz79BRtwa) to talk about things there. I just wanted to give you some sort of heads-up for your behaviour and don't plan on having any further discussion regarding it on the issue trackers.

**Comment by H-A-M-G-E-R** [comment]
i hate discord i need an alternative on revolt.chat
